name: ape-examples
channels:
  - defaults
  - conda-forge
dependencies:
    - pip=25.2
    - python=3.12.8
    - pip:
        - --extra-index-url https://pkgs.dev.azure.com/archipelagos-labs/public-packages/_packaging/ape-python-common/pypi/simple/
        - --extra-index-url https://pkgs.dev.azure.com/archipelagos-labs/public-packages/_packaging/ape-python-client/pypi/simple/
        - ape-python-client==0.0.109